package com.aritr.zinely.ui.theme

import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import com.aritr.zinely.ui.R

/**
 * The **V2.1 three-role type foundation** — Voice, Editorial, Work.
 *
 * [V21-SPEC.md §4.2](docs/design/V21-SPEC.md), frozen 2026-08-10 by
 * [ADR-099](docs/DECISIONS.md#adr-099).
 *
 * | Role | Face | Sets |
 * |---|---|---|
 * | [Voice] | Averia Sans Libre 400/700 | headings, screen titles, the maker's own short strings |
 * | [Editorial] | Fraunces 400/500 | long-form zine body, captions, pull quotes, guide prose |
 * | [Work] | Inter 400/500/600/700 | every control, label, chip, number and piece of chrome |
 *
 * ### This required a constitutional amendment, and that is worth knowing here
 *
 * [V2-CONSTITUTION.md](docs/design/V2-CONSTITUTION.md) §III read *"Fraunces (voice/display) + Inter
 * (work/body). Permanent… **No third UI typeface.** This pairing is fixed across V2."* [Voice] is a
 * third UI typeface. ADR-099 was written asserting it changed nothing in the Constitution, which was
 * false; the conflict surfaced while this file was being written, and the owner amended §III as an
 * explicit act on 2026-08-10 rather than let an ADR carry it implicitly
 * ([Amendment 1](docs/design/V2-CONSTITUTION.md#amendment-log)).
 *
 * Two consequences bind this file:
 *
 * 1. **Fraunces was not dropped, it was re-roled.** It moves from *voice/display* to *editorial* —
 *    the job its long-form cuts were already doing. Do not treat [Editorial] as legacy.
 * 2. **The imperfect face never sets running text.** This is now constitutional text, not advice.
 *    Averia is generated by averaging handwriting samples; its wobble is structural, and structural
 *    wobble across a paragraph is how "handmade" becomes "amateur". [Voice] is for short strings.
 *    **A [Voice] style applied to body copy is a constitutional violation, not a style preference.**
 *
 * ### No type scale, for the same reason [ZinelyV2Fonts] publishes none
 *
 * V2.1 publishes a radius scale and a spacing scale ([ZinelyV21Dimens]) because its corpus has them.
 * It does **not** publish a type scale, because the corpus does not: sizes are chosen per component,
 * and inventing a ladder here would put a second source of truth beside the frozen HTML. Components
 * carry their own size, weight, line-height and tracking from their frozen address.
 *
 * ### Bundled, never fetched
 *
 * All three families ship in `res/font/` under SIL OFL 1.1 (licences in `assets/fonts/`). The
 * prototypes' `fonts.googleapis.com` link tag is prototype scaffolding and has no Compose equivalent
 * by construction: a CDN font request is a network request, and the privacy invariant forbids one.
 *
 * Averia is bundled from the **upstream OFL release**, not from the Google-Fonts-served build the
 * prototypes inline — 231 codepoints against 213, and **123.6 KB deflated in the APK**. Subsetting was
 * measured and rejected: it saves 7.7 KB, because the face is already Latin-only
 * ([V21-SPEC §3.1](docs/design/V21-SPEC.md)).
 *
 * 123.6 KB is the **only** figure taken from a built APK. Two earlier numbers circulated — 116.0 KB (the
 * prototypes' pre-subset bytes) and 121.9 KB (a local `zlib.compress(level=9)` estimate) — and both were
 * quoted as measurements. AAPT's deflate is not `zlib`. Quote 123.6.
 */
public object ZinelyV21Fonts {

    /**
     * `--voice` — **Averia Sans Libre**, 400 and 700, the two weights the corpus uses.
     *
     * The handmade read does not survive without it: Fraunces can be warm but it cannot be wonky, and
     * the wobble is the entire difference between "tasteful" and "made by a person". Short strings
     * only — see the class docs.
     */
    public val Voice: FontFamily = FontFamily(
        Font(R.font.averia_sans_libre_regular, FontWeight.Normal),
        Font(R.font.averia_sans_libre_bold, FontWeight.Bold),
    )

    /**
     * `--serif` — **Fraunces at 400, and only 400.**
     *
     * Re-roled by Amendment 1 from V2's *voice/display* to editorial. Every one of the seven
     * `--serif` rules in the corpus takes the default weight — `.cv .sub`, `.b`, `.pull`, `.zlist`,
     * `.backc p`, `.foldcap` in the Proof and `.t-body` in the Bench — because V2.1's headings are
     * [Voice] now, and headings were what V2's heavier serif cuts existed to set.
     *
     * A first draft of this file bundled Medium/500 as well, by analogy with [ZinelyV2Fonts.Voice]'s
     * three cuts. A review caught it: **no V2.1 rule sets it.** Bundling a weight the specification
     * does not use is precisely the "dead token" failure D-006 deleted `--r` for, and it would make
     * a 500 reachable that the design never chose. 500 and 600 remain available through
     * [ZinelyV2Fonts] for the V2 surfaces not yet re-skinned.
     */
    public val Editorial: FontFamily = FontFamily(
        Font(R.font.fraunces_regular, FontWeight.Normal),
    )

    /**
     * `--sans` — **Inter**, 400/500/600/700. Every control, label, chip and number.
     *
     * Unchanged from V2 in both role and weights. Declared here rather than aliased to
     * [ZinelyV2Fonts.Work] for the same reason that one is not aliased to V1's: same font, no shared
     * lifetime, so retiring a layer stays a file deletion rather than an edit to a live one.
     */
    public val Work: FontFamily = FontFamily(
        Font(R.font.inter_regular, FontWeight.Normal),
        Font(R.font.inter_medium, FontWeight.Medium),
        Font(R.font.inter_semibold, FontWeight.SemiBold),
        Font(R.font.inter_bold, FontWeight.Bold),
    )
}
