package com.aritr.zinely.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawWithContent
import androidx.compose.ui.graphics.BlendMode
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.ImageShader
import androidx.compose.ui.graphics.ShaderBrush
import androidx.compose.ui.graphics.TileMode
import androidx.compose.ui.graphics.drawscope.Fill
import androidx.compose.ui.graphics.isSupported
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.res.imageResource
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.aritr.zinely.ui.R

/**
 * The **V2.1 grain** — the same idea as [ZinelyV2Grain] and not the same material.
 *
 * V2.1 re-authored the noise rather than inheriting it, and every parameter moved:
 *
 * | | V2 | V2.1 |
 * |---|---|---|
 * | `baseFrequency` | .9 | **.85** |
 * | `numOctaves` | 2 | **3** |
 * | tile | 140 | **160** |
 * | `stitchTiles` | `stitch` | **absent** |
 * | baked `opacity` | .5 (Bench/Proof only) | **.42, in all three** |
 *
 * Lower frequency with a third octave is a coarser, more structured grain — visibly closer to paper
 * stock than to sensor noise, which is the direction the whole re-freeze went. The tile is generated by
 * the same transcription of the SVG 1.1 normative algorithm, at
 * [`tools/grain/gen_grain.py`](tools/grain/gen_grain.py), now taking a preset name so neither tile can
 * be produced by editing a constant and forgetting to put it back. **Regenerating V2's tile through the
 * refactored generator reproduces the committed PNG byte-for-byte** (sha256 `91da701d…`), which is what
 * makes the shared generator safe.
 *
 * `stitchTiles` is **absent** here, so the tile is generated unstitched and its edges genuinely do not
 * meet. The generator asserts it in the mirror direction — an unstitched preset that produced a
 * *continuous* function would mean the stitched path had leaked in, which is silently better-behaved
 * and silently not the specification. As [ZinelyV2Grain] records, no pixel statistic separates the two
 * at this frequency; the difference is in what the source asked for.
 *
 * ### Two blend modes — and, measured, the same API floor
 *
 * V2.1 blends **chrome** `soft-light` and **paper** `multiply`. V2 blends all ten of its grain rules
 * `soft-light`, so this really is a second material, not a restyle.
 *
 * It does **not** buy a lower API floor, though the reasoning that it should is seductive enough to be
 * worth recording. `multiply` has a `PorterDuff` equivalent and predates `android.graphics.BlendMode`
 * (API 29), so it looks as though V2.1's paper ought to keep its grain where V2's could not. This file
 * claimed exactly that until [ZinelyV21GrainTest] was run at `sdk = 24` and disagreed: Compose's
 * `BlendMode.isSupported()` reports **false below API 29 for `multiply` as well**. The claim was
 * written from what the platform ought to do rather than from what it does.
 *
 * So [IsSupported] is one predicate, and **D-014 carries over unchanged**: below API 29 the grain draws
 * nothing and the surface stays flat. Do not emulate it with another blend and do not substitute a
 * static tint — an approximation of a material is a second material, and this design has two already.
 * Users on API 24–28 see V2.1's paper without its grain: a **Known Limitation** for the release notes,
 * as it is for V2.
 *
 * Asked of Compose rather than of `Build.VERSION`, for the reason [ZinelyV2Grain.IsSupported] gives —
 * the predicate cannot drift from the compositing path it guards. Which is what caught this.
 *
 * ### Strength stays at the call site
 *
 * Two numbers multiply into what a surface shows — [BakedAlpha], baked into the SVG's `<rect>`, and the
 * element's own CSS `opacity`. The effective column is the only fair comparison:
 *
 * | Surface | Tile | CSS | Blend | **Effective** |
 * |---|---|---|---|---|
 * | Library `.grainy::before` (the desk) | 160 | .55 | soft-light | **0.231** |
 * | Library `.cover .fill::after` | 130 | .5 | multiply | **0.210** |
 * | Proof `.stagewrap::before` | 160 | .35 | soft-light | **0.147** |
 * | Proof `.leaf::after` | 130 | .4 | multiply | **0.168** |
 * | Bench `.page::after` | 130 | .35 | multiply | **0.147** |
 *
 * `.phone::after` is the prototype's studio ground, not an in-app surface, and is excluded on the same
 * reasoning that excluded `--stage` from the palette. Per-surface by the D-007 ruling, so these stay at
 * their call sites rather than becoming tokens.
 *
 * ### What a rendered surface shows, and what predicts it
 *
 * Measured off the parity rasters rather than assumed, and **rewritten after a review falsified the
 * first model**. The tile is RGBA: the noise lives in *both* its luma and its alpha, so the quantity a
 * `multiply` at effective alpha *a* over a base of luma *B* modulates is `a · α · (1 − l)`, not `a · l`.
 * Measured over the tile: luma `mean 0.7322, sd 0.0598`; alpha `mean 0.5002, sd 0.1185`; and
 * `sd(α · (1 − l)) = 0.04232`. Drawing the 160px tile at 130dp resamples it bilinearly, which averages
 * neighbours of a field whose lattice cell is ~1.2px and costs a further factor of **0.624** — measured
 * on the resampled tile, not inferred. Together: `sd ≈ B × 0.21 × 0.04232 × 0.624`.
 *
 * | Surface | base (Rec.709) | predicted sd | measured sd |
 * |---|---|---|---|
 * | `.ink-leaf` | 105.1 | 0.600 | **0.643** |
 * | `.paper-s` | 246.9 | 1.370 | **1.382** |
 *
 * The means match to within 0.03/255, which is the load-bearing part: it proves the effective alpha
 * `0.21 = 0.42 × 0.5` is applied **exactly once**, so no double-multiplication or dropped factor is
 * hiding in the chain. The sds land within 7% and 1%.
 *
 * An earlier version of this section quoted a single luma sd, found rendered contrast at *half* its
 * prediction, and named resampling as the whole cause. Two of those three were wrong: the model omitted
 * alpha entirely, and resampling is 0.624 rather than 0.50. **The conclusion survives** — the shortfall
 * against a naive prediction is parity, not a defect, because `background-size:130px 130px` makes the
 * browser resample the same 160px tile the same way. Do **not** "correct" it by raising the alpha: that
 * would diverge from the specification to match an arithmetic prediction the specification never made.
 * Recorded because the cheapest proof that the grain is drawing at all is to sample a rendered surface
 * and compare — a question a flat-looking ink cover genuinely raises.
 *
 * Note the ratio V2 had and V2.1 does not: V2's Library asked for grain **four to seven times** stronger
 * than any Bench or Proof surface, ruled deliberate as **D-013**. V2.1's five surfaces span 0.147 to
 * 0.231 — a factor of 1.6. The re-freeze closed that gap without being asked to, and a future reader
 * should not "restore" it.
 */
public object ZinelyV21Grain {

    /** The tile's own size. Every `background-size` in the corpus is a rescaling of this one source. */
    public val SourceTileSize: Dp = 160.dp

    /**
     * The alpha baked into the `<rect>` of the `--grain` data URI — `.42`, and unlike V2 it is the same
     * in all three prototypes. A surface transcribing an effective strength says `BakedAlpha * css`
     * and stays bound to this file.
     */
    public const val BakedAlpha: Float = 0.42f

    /** Chrome grain — the desk, the stage. Blends with what is already painted beneath. */
    public val ChromeBlend: BlendMode = BlendMode.Softlight

    /** Paper grain — covers, pages, the leaf. `multiply` darkens where the noise is dark, like ink. */
    public val PaperBlend: BlendMode = BlendMode.Multiply

    /**
     * Whether this device can blend either grain. **False below API 29, for both modes** — measured,
     * not assumed; see the class docs. One predicate because the answer is one answer.
     */
    public val IsSupported: Boolean
        get() = ChromeBlend.isSupported() && PaperBlend.isSupported()
}

/**
 * A repeating, density-correct brush over the V2.1 grain tile.
 *
 * @param tileSize the surface's own frozen `background-size` — 160dp for chrome, 130dp for paper.
 */
@Composable
public fun rememberZinelyV21GrainBrush(tileSize: Dp = ZinelyV21Grain.SourceTileSize): ShaderBrush {
    val image = ImageBitmap.imageResource(R.drawable.zinely_v21_grain)
    val tilePx = with(LocalDensity.current) { tileSize.toPx() }
    return remember(image, tilePx) {
        val shader = ImageShader(image, TileMode.Repeated, TileMode.Repeated)
        // nodpi, so the tile arrives at its authored 160px. Scale to the dp size the surface asks for:
        // without this the grain is finer on a dense screen than on a sparse one, which is the one
        // thing a material must never do — it would read as a different paper stock per device.
        val scale = tilePx / image.width
        shader.setLocalMatrix(android.graphics.Matrix().apply { setScale(scale, scale) })
        ShaderBrush(shader)
    }
}

/**
 * Draw the V2.1 grain over this surface's own content.
 *
 * Takes the brush rather than building one, so this stays an ordinary `Modifier` factory — a
 * `@Composable` modifier cannot be hoisted, keyed or reused, and [rememberZinelyV21GrainBrush] is
 * already the seam for the part that needs composition.
 *
 * A no-op below API 29, for either blend — see [ZinelyV21Grain.IsSupported]. Guarded on the blend
 * actually being drawn rather than on the object's predicate, so the two cannot disagree.
 *
 * @param alpha the **effective** strength — [ZinelyV21Grain.BakedAlpha] × the element's CSS `opacity`,
 *   per the table on [ZinelyV21Grain].
 * @param blend [ZinelyV21Grain.PaperBlend] for anything that is paper, [ZinelyV21Grain.ChromeBlend] for
 *   the room around it. Required rather than defaulted: V2.1 has two materials and picking the wrong
 *   one is a design error that still renders, which is exactly the kind a default would hide.
 */
public fun Modifier.zinelyV21Grain(brush: ShaderBrush, alpha: Float, blend: BlendMode): Modifier =
    if (!blend.isSupported()) {
        this
    } else {
        drawWithContent {
            drawContent()
            drawRect(brush = brush, alpha = alpha, blendMode = blend, style = Fill)
        }
    }
